#!/bin/sh

if [ "$(git branch --show-current)" = master ]; then
  VERSION="v$(grep -oP '^__version__ = "\K\d(\.\d){2}' cmake-init/__main__.py)"
  if [ -n "$(git ls-remote --tags origin "${VERSION}")" ]; then
    echo "${VERSION} already exists remotely, bump the version" >&2
    exit 1
  fi
  if [ -z "$(git tag -l "${VERSION}")" ]; then
    echo "Missing tag ${VERSION}" >&2
    git tag "${VERSION}"
    exit 1
  fi
fi

exit 0
